version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: DockerProd
    container_name: nest_api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/meubanco # Ajuste o nome do banco conforme necessário
  mongodb:
    image: mongo:7.0
    container_name: mongo_db
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
